### ISSUE TITLE
Can't link to MSFS SDK

### ISSUE THREAD

**Issue by madvic2019** [scott-vincent/instrument-data-link#1]
Hi, I'm a total newbie with this,
I've installed FSX SDK SP2, but when I try to compile the instrument panel data link project I get the error (sorry it's in Spanish)

Error	MSB4019	No se encontró el proyecto "C:\Users\MSFS SDK\SimConnect SDK\VS\SimConnectClient-static.props" importado. Confirme que la expresión de la declaración Import "..\..\..\..\..\MSFS SDK\SimConnect SDK\VS\SimConnectClient-static.props" es correcta y que el archivo existe en el disco.	instrument-data-link	C:\Users\victor\source\repos\instrument-data-link\instrument-data-link\instrument-data-link.vcxproj	70	

The point is that I don't find any folder with name "MSFS SDK"  in my computer.

Thanks in advance

**Comment by scott-vincent** [comment]
I built it for FS2020 so you want the FS2020 SDK which you get by going into the game then Options -> General -> Developers and turn on developer mode. Then select SDK Installer from the Help menu that appears at the top of the window. This will download the SDK to C:\MSFS SDK which is where the project expects to find it.

**Comment by scott-vincent** [comment]
Alternatively, just use my pre-built version which is already linked with the static SDK so you don't need to download it.

**Comment by madvic2019** [comment]
Thanks!. I made it work with some tweaking.

Thanks a lot

**Comment by madvic2019** [comment]
Maybe let the prebuilt version be visible in the repo

**Comment by scott-vincent** [comment]
Yes, the prebuilt version is available in the repo. It's standard GitHub. Just look under Releases.
