### ISSUE TITLE
Slow loading of MSFS2020

### ISSUE THREAD

**Issue by alexandrehardy** [scott-vincent/instrument-data-link#10]
Thanks for making this open source!

After running instrument data link v1.6.2, and then starting MSFS2020, the MSFS2020 load time is significantly longer (not measured precisely, but about 10x slower). The game performance seems fine, but the load times are excruciating.

If instrument data link v1.6.2 is terminated, then MSFS2020 goes back to normal load times.

Any ideas why this might be?  This is after updating MSFS2020 on 18 June 2022.

In this case no external program had yet connected to instrument-data-link, but from what I read in the code this shouldn't be a problem.

Any ideas why the load time is affected in this way?

**Comment by scott-vincent** [comment]
No, it doesn't even go in the Community folder, it just uses SimConnect so there's no way it can affect loading times. I think there must be a different cause you need to track down.

**Comment by alexandrehardy** [comment]
Thanks, I was hoping you had seen this before :-).

I would have hoped that MSFS2020 was written in a way that SimConnect wouldn't be able to have that effect on MSFS2020, but apparently my hopes were too high.
