### ISSUE TITLE
Kudos!

### ISSUE THREAD

**Issue by pfrench42** [scott-vincent/instrument-data-link#3]
Just want to say this is a great project!

Elegant design, and a powerful link for doing homebrew upgrades to fs2020.

I'm considering doing a midi bridge that attaches to this, then you could plug cheap devices like the Korg NanoControl and use them to control things like the G1000

I'm currently trying to get instrument-panel running on the odroid c2, it compiled and ran but I got the MALI error.
I had to upgrade it to ubuntu 20 LTS and zotted it in the process, once it's recovered and running this on a second display I'll take a look at MIDI learn

**Comment by scott-vincent** [comment]
Thanks. Glad you like it and find it useful.
